[tool.poetry]
name = "jinja2-git"
version = "0.2.0"
description = "Jinja2 extension to handle git-specific things"

license = "MIT"

authors = [
    "Nikita Sobolev <mail@sobolenv.me>",
    "Mikhail Akimov <daggerito@gmail.com>"
]

readme = "README.md"  # Markdown files are supported

repository = "https://github.com/sobolevn/jinja2-git"
homepage = "https://github.com/sobolevn/jinja2-git"

keywords = [
    "jinja2",
    "jinja2-extension",
    "jinja2-plugin",
    "git",
]

classifiers=[
        'Development Status :: 3 - Alpha',
        'Environment :: Console',
        'Intended Audience :: Developers',
        'License :: OSI Approved :: MIT License',
        'Operating System :: OS Independent'
    ]

[tool.poetry.dependencies]
python = "~2.7 || ^3.6 || ^3.7"
jinja2 = "^2.10"


[tool.poetry.dev-dependencies]
flake8 = "^3.5"
flake8-builtins = "^1.4"
flake8-commas = "^2.0"
flake8-quotes = "^1.0"
flake8-pep3101 = "^1.2"
flake8-comprehensions = "^1.4"
flake8-blind-except = "^0.1"
flake8-docstrings = "^1.3"
flake8-pytest = "^1.3"
pytest = "^3.0"
pytest-cov = "^2.6"
pytest-isort = "^0.2.1"
pytest-flake8 = "^1.0"
pep8-naming = "^0.7"
